package:
  name: rio-terrain
  version: 0.0.28

source:
  git_url: ../
  git_rev: head

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - aspect = rio_terrain.cli.aspect:aspect
    - close = rio_terrain.cli.close:close
    - curvature = rio_terrain.cli.curvature:curvature
    - difference = rio_terrain.cli.difference:difference
    - extract = rio_terrain.cli.extract:extract
    - mad = rio_terrain.cli.mad:mad
    - quantiles = rio_terrain.cli.quantiles:quantiles
    - slice = rio_terrain.cli.slice:slice
    - slope = rio_terrain.cli.slope:slope
    - std = rio_terrain.cli.std:std
    - threshold = rio_terrain.cli.threshold:threshold
    - uncertainty = rio_terrain.cli.uncertainty:uncertainty

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - rasterio
    - click
    - crick 

test:
  imports:
    - rio_terrain
  commands:
    - rio aspect --help
    - rio curvature --help
    - rio difference --help
    - rio extract --help
    - rio mad --help
    - rio quantiles --help
    - rio slice --help
    - rio slope --help
    - rio std --help
    - rio threshold --help
    - rio uncertainty --help

about:
  home: https://github.com/mrahnis/rio-terrain
  description: Rasterio CLI plugin to perform common operations on single-band elevation rasters
  license: BSD
  license_file: LICENSE.txt
