{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: rio-terrain
  version: {{ version }}

source:
  git_url: ../
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - aspect = rio_terrain.cli.aspect:aspect
    - labelbounds = rio_terrain.cli.labelbounds:labelbounds
    - compare = rio_terrain.cli.compare:compare
    - copynodata = rio_terrain.cli.copynodata:copynodata
    - curvature = rio_terrain.cli.curvature:curvature
    - difference = rio_terrain.cli.difference:difference
    - extract = rio_terrain.cli.extract:extract
    - fillnodata = rio_terrain.cli.fillnodata:fillnodata
    - mad = rio_terrain.cli.mad:mad
    - quantiles = rio_terrain.cli.quantiles:quantiles
    - slice = rio_terrain.cli.slice:slice
    - slope = rio_terrain.cli.slope:slope
    - std = rio_terrain.cli.std:std
    - subdivide = rio_terrain.cli.subdivide:subdivide
    - threshold = rio_terrain.cli.threshold:threshold
    - uncertainty = rio_terrain.cli.uncertainty:uncertainty

requirements:
  build:
    - python
    - setuptools
  run:
    {% for dependency in pyproject['project']['dependencies'] %}
    - {{ dependency.lower() }}
    {% endfor %}

test:
  imports:
    - rio_terrain
  commands:
    - rio aspect --help
    - rio compare --help
    - rio copynodata --help
    - rio curvature --help
    - rio difference --help
    - rio extract --help
    - rio fillnodata --help
    - rio label --help
    - rio labelbounds --help
    - rio mad --help
    - rio quantiles --help
    - rio slice --help
    - rio slope --help
    - rio std --help
    - rio subdivide --help
    - rio threshold --help
    - rio uncertainty --help

about:
  home: https://github.com/mrahnis/rio-terrain
  description: Rasterio CLI plugin to perform common operations on single-band elevation rasters
  license: BSD
  license_file: LICENSE.txt

# https://github.com/conda/conda-build/issues/4807
# whatever_you_do_don't_load_setup_py_dataxxx!!!
